### PR TITLE
adds terraform option to flag nested hypervisor in virtual machines

### PR DESCRIPTION
**Pull request by kradalby**
Adds terraform option to enable/disable nested hypervisor within a virtual machine.

Depends on:
https://github.com/UKCloud/govcloudair/pull/16

### CODE REVIEW

**Comment by pasikarkkainen** [comment]
@lvirbalas : Hi! I noticed you guy have been active with the fixes and new features. This PR would be nice to have merged aswell.

**Comment by kradalby** [comment]
@pasikarkkainen This patch is merged in my fork of the project; https://github.com/vCloud/terraform-provider-vcd

I currently try and plan to do some more on this, but currently I have a lot of the features we need so it is a bit on hold.

**Comment by pasikarkkainen** [comment]
@kradalby : great, thanks a lot for the update! Looking forward to all the goodies :)

**Comment by kradalby** [comment]
@pasikarkkainen Actually, looking at the user you tagged, it looks like VMware has started to properly work on it. Both the go vcloud library and the provider. As far as I can see, they are 3-4 developers so they might surpass my fork quickly, which is superb and we might get a properly supported provider.

**Comment by pasikarkkainen** [comment]
@lvirbalas : Nested Hypervisor flag is used to expose (virtual) VT-x / AMD-v CPU virtualization feature to the guest VM. That allows running things like desktop virtualization products/tools (like VMware Player or VMware Workstation) in the VM, running various development/devops tools like Vagrant/Virtualbox in the VM, or even running virtual ESXi VMs for dev/QA/lab/testing usage.

So being able to expose nested hypervisor flag for VMs is important for many workloads!

**Comment by lvirbalas** [comment]
@pasikarkkainen thank you for a good writeup. Would you be willing to generate a PR into vmware-takes-ownership branch directly, so this functionality gets in into master once we merge the branch?

**Comment by pasikarkkainen** [comment]
@kradalby : Hey. Any chance you could refresh and create a PR against vmware-takes-ownership branch?

@lvirbalas : Actually I'd prefer @kradalby to create the PR, he's the author of the patch(es).. I can take a look if he can't do it.

**Comment by kradalby** [comment]
I’m on vacation this week, I can have a look when I get back.

That said most of my work consisted of rewriting big parts of both the govdc lib and the provider. And since you guys started from head on the old ones I might need to start from scratch.

I’ll have a look.

**Comment by kradalby** [comment]
@lvirbalas Hi, I've taken a look to get a bit up to date and I was wondering if there were any public information on where the project is heading? I don't mind adding the NestedVirtualization to the current project.

But currently, with the way the Terraform resources is structured and how it works, it is not a project I will consider using for our infrastructure and I will stick with our/my fork.

I don't want anything more than a good supported version officially from VMware, but the current setup with VM parameters both inside a vApp and a VM and so much double code, it is very cumbersome to work on (and I have done a lot of work on it a year ago :P ).

I don't necessarily think the direction I took is the best, its just the one that fitted our needs. And if possible i would love to contribute and discuss this as well, are you guys available somewhere for chatting?

**Comment by lvirbalas** [comment]
@kradalby Yes, of course. Please try joining our Slack channel vcd-terraform-dev at vmwarecode.slack.com workspace and let's have a call :) I hope https://code.vmware.com/join has enough information to help with that. I'm curious to understand your point better.

> I don't want anything more than a good supported version officially from VMware
Overall, VMware has taken that effort now and you can see that in the mentioned branch. It will become fully official after the branch gets merged to master. Hence, it would be pretty cool to have your contribution in as well!

**Comment by pasikarkkainen** [comment]
@kradalby now the big PR to merge all the vmware work to master branch is out: https://github.com/terraform-providers/terraform-provider-vcd/pull/143

It'd be great if you could rebase the nested hypervisor feature on top of that.

**Comment by pasikarkkainen** [comment]
@kradalby And now the big changes are merged to master. Any chance you could port the nested hypervisor feature to apply against master branch?

**Comment by dataclouder** [comment]
If we want to merge this feature, it should be integrated into the current code.
Please resolve the current conflicts, and then we'll review.

**Comment by pasikarkkainen** [comment]
@kradalby Hi! Is it likely you'll have time to work on this PR, or should someone else take over? Thanks.

**Comment by kradalby** [comment]
@pasikarkkainen I have implemented a suggestion now, but I need to test it.

I think I will manage to test it this week, but I only have vCloud in the office and not on my own servers.

**Comment by pasikarkkainen** [comment]
@kradalby sounds good! let me know if you want me to test aswell. Thanks.

**Comment by pasikarkkainen** [comment]
It seems v2.1 has been released, and all the latest changes are now on master branch. I'm happy to test the nester hypervisor feature when you push the changes to this PR :)

**Comment by lvirbalas** [comment]
> @pasikarkkainen I have implemented a suggestion now, but I need to test it.
> 
> I think I will manage to test it this week, but I only have vCloud in the office and not on my own servers.

@kradalby Are you planning to finish this one or would you like us to do it? We are in good position to take this functionality in now that v2.1.0 is out the door.

**Comment by Didainius** [comment]
@kradalby, ping. Are you still progressing. I can soon resume this and move towards merging if you are not?

**Comment by vbauzysvmware** [comment]
P.s. I found the code `configureVMWorkaround` https://github.com/terraform-providers/terraform-provider-vcd/pull/74/commits/f3308ea0809192797c7531ed8a0a40d08adbf07a which should be checked, cause mentioned different behaviour with older vCD versions.

**Comment by Didainius** [comment]
I'm closing this one in favor of  #219 to track work across both repos.

**Comment by kradalby** [comment]
Sorry guys, I have been flooded lately. Both at work and personal. If my employer deem it reasonable to help contributing I will join in again, but if I cant do it properly, I don't think I should. Sorry for the long wait for reply.

**Pull request closed without merging**
