### PR TITLE
Switch to go modules and Terraform 0.11

### PR DESCRIPTION
**Pull request by dataclouder**
Switch to Go modules and Terraform 0.11

* Delete the vendor directory
*    Add `go.mod` and `go.sum`
*    Change Travis instructions
*    Remove vendor references from `GNUmakefile` and scripts
*    Disable `errcheck.sh`, as it does not support modules
*    Add script web-site.sh to run website operations without vendor
*    Add deprecation message to `resource_vcd_network.go`
*    Remove expected failure from `resource_vcd_network_test.go`
*    Change requirements in `README.md`

Note: The initial `go.mod` was simply:

```go
module github.com/terraform-providers/terraform-provider-vcd

require (
	github.com/hashicorp/terraform v0.11.11
	github.com/vmware/go-vcloud-director v2.1.0-alpha.1
)
```
However, the final line for `go-vcloud-director` was:

```go
    // [...]
    github.com/vmware/go-vcloud-director v0.0.0-20190212133417-3f06ee3b7592
```
In a previous experiment (see [closed PR](https://github.com/terraform-providers/terraform-provider-vcd/pull/168), the tag was preserved in the final `go.mod`.)
We need to investigate the reason.

### CODE REVIEW

**Comment by vbauzysvmware** [comment]
Issue identified. No wories.
I checked go.sum after deleting cache and file. New one created was with:
```
github.com/vmware/go-vcloud-director v0.0.0-20190212133417-3f06ee3b7592 h1:eQSrP1ii7yt/hfASw9bLiFZfOlTqJSM9n2YVaEi3zbs=
github.com/vmware/go-vcloud-director v0.0.0-20190212133417-3f06ee3b7592/go.mod h1:dbrnxd2uJ7PnbqcL04gVv2t9fZTbEGtr19sy+zPLHRc=
```

**Comment by lvirbalas** [comment]
> github.com/vmware/go-vcloud-director v0.0.0-20190212133417-3f06ee3b7592

@Didainius suggested possible solutions in another thread. We need him in reviewers of this PR, but I don't see a way to add him yet.

**Comment by Didainius** [comment]
Moved to modules with #178 and migrating to Terraform 0.11.11 with #181.

**Comment by vbauzysvmware** [comment]
@Didainius  Don't forget to close after your merge

**Comment by Didainius** [comment]
Moved to modules with #178 and migrated to Terraform 0.11.13 with #181.

**Pull request closed without merging**
