### PR TITLE
Update repository to use Go modules

### PR DESCRIPTION
**Pull request by dataclouder**
This is a preliminary change to support go modules and Terraform 0.11 (current master uses 0.10).

It is not intended to be merged soon, but rather to provide a playground for the team to try this setup before adopting it on a stable basis.

Related Issue #162 

How to try the same setup on your own without using this branch:

1. Upgrade Go to 1.11.4+
2. clone your repository **outside the $GOPATH**
3. ` git checkout vmware-stash-while-master-pr-open`
4. `git checkout -b try-modules` # or any branch name that you like
5. `git rm -r vendor`  # You will see a bunch of files being deleted here
6. create the file `go.mod` with the following contents:
```go
module github.com/terraform-providers/terraform-provider-vcd

require (
	github.com/hashicorp/terraform v0.11.11
	github.com/vmware/go-vcloud-director v2.1.0-alpha.1
)
```
7. `make test`

You will see that Go will collect the repositories needed to satisfy `go.mod`, and will also update the file with more items and create a file named `go.sum` with the checksums for the repositories being loaded.
The repositories referred in `go.mod` will end up in `$HOME/go/pkg/mod`: both source and compiled objects will be there.

**IMPORTANT**: I have tried to leave the `vendors` folder in place, but its contents are so confusing that I did not manage to get a clean compilation. 

NOTE for reviewers: `go.sum` is generated during `go build`. If you want to change it, you need to change `go.mod`.

**TO DO**: 
* Update documentation about minimum Go version required.
* Insert deprecation messages in resources (supported by Terraform 0.11)

### CODE REVIEW

**Comment by vbauzysvmware** [comment]
I followed your guideline and everything worked. And when tried `make testacc` I got issues that modules ins't found in the path. I tried various ways but didnt' find correct `export GOPATH=/home/...` variation to work. Could you help me ?
Also GNU make file needs update cause using still vendor stuff.

**Comment by vbauzysvmware** [comment]
Additional thing: we need to plan moving govcd together

**Comment by vbauzysvmware** [comment]
Please investigate `go.sum` if it should be commited or personal generated env file.

**Comment by dataclouder** [comment]
> Please investigate `go.sum` if it should be commited or personal generated env file.

[Yes. We should keep it in the repo](https://github.com/golang/go/wiki/Modules#should-i-commit-my-gosum-file-as-well-as-my-gomod-file)

**Comment by dataclouder** [comment]
I am closing this PR and creating a new one after the go-vcloud-director switch.

**Pull request closed without merging**
