### PR TITLE
[AUTOMATED] Upgrade to Go 1.11

### PR DESCRIPTION
**Pull request by appilon**

### CODE REVIEW

**Comment by lvirbalas** [comment]
Just noticed this PR, while @Didainius just finished the Go modules migration in the vmware-stash-while-master-pr-open branch. @Didainius please check if there's something in this PR that could still be needed.

**Comment by Didainius** [comment]
@appilon, what tool did you use to remove the extraneous struct types? I'd like to check if this is up to date. We have also changed the docs since then, but I could do this cleanup when I'm migrating dependency to terraform 0.11.11

**Comment by appilon** [comment]
@Didainius `gofmt`
```
$ gofmt -s -w ./vcd
```

**Comment by appilon** [comment]
I'm going to close this PR in favor of the ones in progress. Let me know if I can assist at all in the changeover to go1.11 and modules!

**Comment by lvirbalas** [comment]
@appilon now that you mentioned it, we actually do need your help in one review #183 - thanks in advance!

**Pull request closed without merging**
