### PR TITLE
Add support for changing root disk size

### PR DESCRIPTION
**Pull request by cheald**
This depends on https://github.com/vmware/go-vcloud-director/pull/251

This simply adds the ability to specify a `root_disk` parameter when defining a VM, which indicates the disk's size in megabytes. For example:

```javascript
// vm.tf.json
{
  "resource": {
    "vcd_vapp_vm": {
      "az-app1": {
        "name": "az-app1",
        "root_disk": 256000,
        // ...
      }
    }
  }
}
```

### CODE REVIEW

**Comment by cheald** [comment]
I've added the replace clause in go.mod, and it's working as expected locally, but I don't see Travis performing a `go get` or similar; do I need to `go mod vendor` and commit the vendored changes as well? I don't want to clutter up the diff with dependency changes unless that's desired.

**Comment by dataclouder** [comment]
> I've added the replace clause in go.mod, and it's working as expected locally, but I don't see Travis performing a `go get` or similar; do I need to `go mod vendor` and commit the vendored changes as well? I don't want to clutter up the diff with dependency changes unless that's desired.

You need to run `go mod tidy` and `go mod vendor`. Once your change in go-vcloud-director is merged, you will remove the replace, run the above commands again, and all should be well.

**Comment by cheald** [comment]
Thanks! And thanks for your patience - I haven't worked with Go modules before! Still learning the ropes.

**Comment by lvirbalas** [comment]
Thank you @cheald for contributing! I have some usage-based questions:
- How does operating system of the OVA react when you change the size? Have you tried with different OVAs of both Linux and Windows variants? I'd think that there should be cases where only partition gets resized, but the extra space is not instantly accessible from the OS. Would be great if you could elaborate on this aspect with different OVA examples.
- What happens if you reduce the size as opposed to making it larger?

**Comment by vbauzysvmware** [comment]
From perspective point of view. If we can change any disk size in OVA, maybe we should let it in terraform too, not only `root`/first one ?

**Comment by cheald** [comment]
> How does operating system of the OVA react when you change the size?

Under Linux, the larger disk size is immediately reflected via `lslbk`. Filesystems have to be resized to larger extents via `resize2fs` or similar. This is functionally identical to EBS resizing at AWS. I haven't tested it under Windows.

> What happens if you reduce the size as opposed to making it larger?

vCD will not permit this; attempting to shrink a disk results in an API error.

> From perspective point of view. If we can change any disk size in OVA, maybe we should let it in terraform too, not only root/first one ?

That's certainly possible. This work could be expanded into full management of internal disks, to complement the independent disk attachment. The govcd APIs take bus/unit IDs and aren't hardcoded to the root disk, so the Terraform provider would just need additional work to consume it.

(As an aside: how do I kick off a Travis build for my latest push? It didn't seem to happen automatically.)

**Comment by Didainius** [comment]
@cheald,
Sorry for this being silent for so long. We have been busy on rolling out 2.5.0 and got buried under other tasks.

Now we have yet another task #311 which we want to bring in. I am looking at them and thinking - as the root disk is same as any other disk (just mostly often having address `0:0`, but I believe not necessarily for some templates) we could design a structure to accomplish both goals.

What are your thoughts on such proposal? As this may become more time demanding should someone else pick #311 and cover the root disk size functionality as well in the solution of that issue or would you like to bring #311 forward?

**Comment by cheald** [comment]
I'm happy to let you all take it if you'd like. My disk management needs
are pretty simple, and I'm still quite new to vCloud, so someone with a
broader view of the tool may be more suited to take that one over the
finish line. Hopefully my work provides a jump start!

**Comment by vbauzysvmware** [comment]
Hi @cheald. I started work on different approach due that we need support various features, not only `root` internal disk. You can check and give a spin in https://github.com/terraform-providers/terraform-provider-vcd/pull/412 it is still draft.

**Comment by cheald** [comment]
Looking good! I'll close this PR, since it looks like you're headed in a more robust direction. Thank you!

**Pull request closed without merging**
