### PR TITLE
[Improvement] Add multiple networks (supersedes #59)

### PR DESCRIPTION
**Pull request by tlawrence**
ref #59 

This PR is to attempt to fix the issues therein.

### CODE REVIEW

**Comment by tlawrence** [comment]
Multi VM per vApp & Multi NIC are now working but with some bugs.

Logic needs adding to govcloudair vapp.go AddVM and RemoveVM function to rebuild the "NetworkConfigSection" when VMs are added or removed. Otherwise adding nice on network which are not in the list fails. 

Additionally, when I remove a NIC and run terraform apply, The vapp_vm resource is flagged for recreation but deletion of the existing VM fails. Not sure why. 


Possible stretch goal: Work out how to add and remove NICs without recreating VMs.

**Comment by tlawrence** [comment]
@dn1s any comments on this?

**Comment by dn1s** [comment]
Well biggest problem here with this pr and with mine as well is terraform state handling is broken.
Which results in onstant "changed" states when running `terraform plan` for ips of network adapters.

**Comment by dn1s** [comment]
#74 is working for me please use this pr

**Comment by spengilley** [comment]
Will this PR cover multiple networks for the VM?

**Comment by Didainius** [comment]
I believe #177 should give even more than this PR and therefore am closing it. Do ping us if you think otherwise.

**Pull request closed without merging**
