### PR TITLE
Possibility to add OVF parameters to a Vapp.

### PR DESCRIPTION
**Pull request by cgroschupp**
Old PR hashicorp/terraform#8993

### CODE REVIEW

**Comment by bobbydeveaux** [comment]
Sorry @cgroschupp - we now have full CI suite running against master branch, but in the process it looks as though this PR now has conflicts, are you okay to resolve please? :)

**Comment by cgroschupp** [comment]
@bobbydeveaux i have fixed the conflicts

**Comment by pasikarkkainen** [comment]
@cgroschupp : Thanks a lot again! Looking forward to getting this merged :)

**Comment by bobbydeveaux** [comment]
Running CI suite now.

**Comment by bobbydeveaux** [comment]
OK	 TestAccVcdVAppVm_Basic 	13m:06s,946ms 	9
OK	 TestAccVcdVApp_PowerOff 	9m:33s,432ms 	8
OK	 TestAccVcdVAppRaw_Basic 	7m:21s,609ms 	7
OK	 TestAccVcdNetwork_Basic 	2m:53s,832ms 	5
OK	TestAccVcdFirewallRules_basic 	2m:41s,579ms 	4
OK	TestAccVcdDNAT_tlate 	2m:24s,544ms 	2
OK	 TestAccVcdDNAT_Basic 	2m:16s,086ms 	1
OK	TestAccVcdSNAT_Basic 	2m:14s,984ms 	6
OK	TestAccVcdVpn_Basic 	2m:08s,487ms 	3

**Pull request merged**
