### PR TITLE
Added options to configure dhcp lease times

### PR DESCRIPTION
**Pull request by harmjanblok**
Proposal to allow DHCP lease times to be configured, see https://github.com/UKCloud/govcloudair/pull/8 for additional changes.

### CODE REVIEW

**Comment by bobbydeveaux** [comment]
Great. Are you able to commit the changes to the vendor file by running govendor fetch, as I have now merged https://github.com/UKCloud/govcloudair/pull/8 ? 

Cheers

**Comment by harmjanblok** [comment]
Done. ukcloud/govcloudair@0f21764 also includes some unrelated changes regarding `vapp.go`.

**Comment by bobbydeveaux** [comment]
Awesome thanks. CI suite running this now

**Comment by bobbydeveaux** [comment]
Status | Test | Duration | Order#
-- | -- | -- | --
OK | TestAccVcdVApp_PowerOff | 10m:41s,973ms | 8
OK | TestAccVcdVAppVm_Basic | 7m:42s,446ms | 9
OK | TestAccVcdVAppRaw_Basic | 3m:59s,604ms | 7
OK | TestAccVcdNetwork_Basic | 1m:28s,837ms | 5
OK | TestAccVcdFirewallRules_basic | 1m:03s,309ms | 4
OK | TestAccVcdVpn_Basic | 57s,018ms | 3
OK | TestAccVcdDNAT_Basic | 55s,741ms | 1
OK | TestAccVcdDNAT_tlate | 55s,605ms | 2
OK | TestAccVcdSNAT_Basic | 55s,465ms | 6

**Comment by harmjanblok** [comment]
@bobbydeveaux Currently I've some issues creating a VM when using this version:

> Following errors occurred while updating network connections:
There are insufficient IP addresses to complete operation. You need to add IP addresses to the network that is associated with the object being created or deployed.

I'm still trying to find out what causes this issue.

**Comment by harmjanblok** [comment]
The issues I had are unrelated to the changes in this pull request. I'll create a separate issue for that.

**Pull request merged**
