### PR TITLE
fix typo that undeploys vapp instead of vm while deleting a vm

### PR DESCRIPTION
**Pull request by vkhacharia**
Found the pointer in #69 Updated the code and tested locally.

### CODE REVIEW

**Comment by vbauzysvmware** [comment]
Nice catch, still we need to investigate how it related to `vapp.Deploy()` part which start from 875 line.

**Comment by vbauzysvmware** [comment]
If everyone would approve I suggest together with this fix remove 873-894 case. I don't see any more value for deploy if don't undepoy vAPP. My testing seem to verify that. I would like other to verify that.

**Comment by vkhacharia** [comment]
Do I update the changelog and make new pull request?

**Comment by Didainius** [comment]
@vkhacharia NP, I will put in a note with the next PR I have in the oven :)
Thank you again.

**Pull request merged**
