### PR TITLE
Introduces ip allocation entry to select method for IP acquiring.

### PR DESCRIPTION
**Pull request by kradalby**
This is a suggestion to solve #50 and is currently how its implemented for our fork of the provider.

Opinions are welcome!

### CODE REVIEW

**Comment by bobbydeveaux** [comment]
Great work. We'll see if we can get this in, but as per our discussion yesterday, lets see what our grand plan looks like first :)

**Comment by gregswift** [comment]
Any word? its been a while

**Comment by kradalby** [comment]
I’m currently pushing for merging this, and also we are using this ourself.
https://github.com/terraform-providers/terraform-provider-vcd/pull/74

**Comment by Didainius** [comment]
@kradalby, I believe #177 should give even more than this PR and therefore am closing it. Do ping us if you think otherwise.

**Pull request closed without merging**
